import Head from "next/head";
import { useMoralis } from "react-moralis";
import Login from "../components/Login";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Body from "../components/Body";

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();
  if (!isAuthenticated) return <Login />;
  return (
    <div>
      <Head>
        <title>Metaverse - Web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full min-h-screen background">
        <div className="max-w-5xl mx-auto">
          <Navbar />
          <Body />
        </div>
      </div>
    </div>
  );
}
